### ISSUE TITLE
palgate_extract is not working 

### ISSUE THREAD

**Issue by eladsasi** [RoeiOfri/homebridge-palgate-opener#19]
i get Eror 
when i put my phone number 

homebridge@raspberrypi:/var/lib/homebridge $ palgate_extract
Please type your phone number, e.g 054123412345: 0505605908
Traceback (most recent call last):
  File "/usr/bin/palgate_extract", line 106, in <module>
    main()
  File "/usr/bin/palgate_extract", line 75, in main
    assert palgate.initiate_sms(phone_number)
  File "/usr/bin/palgate_extract", line 33, in initiate_sms
    self._validate_res(res)
  File "/usr/bin/palgate_extract", line 51, in _validate_res
    print(res.json()['msg'])
KeyError: 'msg'
homebridge@raspberrypi:/var/lib/homebridge $

**Comment by RoeiOfri** [comment]
This plugin is no longer working.

Please see comment in repo's readme file.
